steps:
  - module_header:
      open_bracket: next_line
      separate_lists: false
      sort: false
  - imports:
      align: group
      pad_module_names: false
      long_list_align: new_line_multiline
      separate_lists: false
  - language_pragmas:
      align: true
