version: '3'

services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    ports:
    - 5432:5432
