name: simpleSurvey
version: 0.0.1
synopsis: A simple survey tool
description: See README at <https://github.com/japiirainen/simple-survey#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/simple-survey
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
    - base

library:
  source-dirs: src
  exposed-modules:
    - SimpleSurvey


executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - simpleSurvey

tests:
  tasty:
    main: Main.hs
    source-dirs: tasty

    dependencies:
      - base
      - tasty
      - tasty-hunit