name: simpleSurvey
version: 0.0.1
synopsis: A simple survey tool
description: See README at <https://github.com/japiirainen/simple-survey#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/simple-survey
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - SimpleSurvey
    - SimpleSurvey.Config
    - SimpleSurvey.Database
    - SimpleSurvey.Init
    - SimpleSurvey.Logger
    - SimpleSurvey.App
    - Util.Database.Persist.Postgresql.Json


executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - simpleSurvey

tests:
  tests:
    main: Main.hs
    source-dirs: tests

    dependencies:
      - base
      - hspec
      - simpleSurvey
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - servant-multipart
  - http-client
  - utf8-string
  - password
  - password-instances
  - password-types
  - persistent
  - persistent-template
  - persistent-postgresql
  - monad-logger
  - monad-metrics
  - esqueleto
  - aeson
  - wai
  - wai-extra
  - text
  - warp
  - http-api-data
  - bytestring
  - containers
  - QuickCheck
  - quickcheck-arbitrary-adt
  - wai-cors
  - mtl
  - katip
  - say
  - fast-logger
  - safe-exceptions
  - safe
  - ekg
  - wai-middleware-metrics
  - resource-pool
  - microlens
  - hspec
  - servant-auth
  - servant-auth-server
  - time
  - quickcheck-text