# This file has been generated by node2nix 1.10.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/code-frame-7.16.7" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.16.7.tgz";
        sha512 = "iAXqUn8IIeBTNd72xsFlgaXHkMBMt6y4HJp1tIaK465CWLT/fG1aqB7ykr95gHHmlBdGbFeWWfyB4NJJ0nmeIg==";
      };
    };
    "@babel/compat-data-7.16.8" = {
      name = "_at_babel_slash_compat-data";
      packageName = "@babel/compat-data";
      version = "7.16.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/compat-data/-/compat-data-7.16.8.tgz";
        sha512 = "m7OkX0IdKLKPpBlJtF561YJal5y/jyI5fNfWbPxh2D/nbzzGI4qRyrD8xO2jB24u7l+5I2a43scCG2IrfjC50Q==";
      };
    };
    "@babel/core-7.16.12" = {
      name = "_at_babel_slash_core";
      packageName = "@babel/core";
      version = "7.16.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/core/-/core-7.16.12.tgz";
        sha512 = "dK5PtG1uiN2ikk++5OzSYsitZKny4wOCD0nrO4TqnW4BVBTQ2NGS3NgilvT/TEyxTST7LNyWV/T4tXDoD3fOgg==";
      };
    };
    "@babel/generator-7.16.8" = {
      name = "_at_babel_slash_generator";
      packageName = "@babel/generator";
      version = "7.16.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/generator/-/generator-7.16.8.tgz";
        sha512 = "1ojZwE9+lOXzcWdWmO6TbUzDfqLD39CmEhN8+2cX9XkDo5yW1OpgfejfliysR2AWLpMamTiOiAp/mtroaymhpw==";
      };
    };
    "@babel/helper-annotate-as-pure-7.16.7" = {
      name = "_at_babel_slash_helper-annotate-as-pure";
      packageName = "@babel/helper-annotate-as-pure";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.16.7.tgz";
        sha512 = "s6t2w/IPQVTAET1HitoowRGXooX8mCgtuP5195wD/QJPV6wYjpujCGF7JuMODVX2ZAJOf1GT6DT9MHEZvLOFSw==";
      };
    };
    "@babel/helper-compilation-targets-7.16.7" = {
      name = "_at_babel_slash_helper-compilation-targets";
      packageName = "@babel/helper-compilation-targets";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-compilation-targets/-/helper-compilation-targets-7.16.7.tgz";
        sha512 = "mGojBwIWcwGD6rfqgRXVlVYmPAv7eOpIemUG3dGnDdCY4Pae70ROij3XmfrH6Fa1h1aiDylpglbZyktfzyo/hA==";
      };
    };
    "@babel/helper-environment-visitor-7.16.7" = {
      name = "_at_babel_slash_helper-environment-visitor";
      packageName = "@babel/helper-environment-visitor";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-environment-visitor/-/helper-environment-visitor-7.16.7.tgz";
        sha512 = "SLLb0AAn6PkUeAfKJCCOl9e1R53pQlGAfc4y4XuMRZfqeMYLE0dM1LMhqbGAlGQY0lfw5/ohoYWAe9V1yibRag==";
      };
    };
    "@babel/helper-function-name-7.16.7" = {
      name = "_at_babel_slash_helper-function-name";
      packageName = "@babel/helper-function-name";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-function-name/-/helper-function-name-7.16.7.tgz";
        sha512 = "QfDfEnIUyyBSR3HtrtGECuZ6DAyCkYFp7GHl75vFtTnn6pjKeK0T1DB5lLkFvBea8MdaiUABx3osbgLyInoejA==";
      };
    };
    "@babel/helper-get-function-arity-7.16.7" = {
      name = "_at_babel_slash_helper-get-function-arity";
      packageName = "@babel/helper-get-function-arity";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-get-function-arity/-/helper-get-function-arity-7.16.7.tgz";
        sha512 = "flc+RLSOBXzNzVhcLu6ujeHUrD6tANAOU5ojrRx/as+tbzf8+stUCj7+IfRRoAbEZqj/ahXEMsjhOhgeZsrnTw==";
      };
    };
    "@babel/helper-hoist-variables-7.16.7" = {
      name = "_at_babel_slash_helper-hoist-variables";
      packageName = "@babel/helper-hoist-variables";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-hoist-variables/-/helper-hoist-variables-7.16.7.tgz";
        sha512 = "m04d/0Op34H5v7pbZw6pSKP7weA6lsMvfiIAMeIvkY/R4xQtBSMFEigu9QTZ2qB/9l22vsxtM8a+Q8CzD255fg==";
      };
    };
    "@babel/helper-module-imports-7.16.7" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.16.7.tgz";
        sha512 = "LVtS6TqjJHFc+nYeITRo6VLXve70xmq7wPhWTqDJusJEgGmkAACWwMiTNrvfoQo6hEhFwAIixNkvB0jPXDL8Wg==";
      };
    };
    "@babel/helper-module-transforms-7.16.7" = {
      name = "_at_babel_slash_helper-module-transforms";
      packageName = "@babel/helper-module-transforms";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.16.7.tgz";
        sha512 = "gaqtLDxJEFCeQbYp9aLAefjhkKdjKcdh6DB7jniIGU3Pz52WAmP268zK0VgPz9hUNkMSYeH976K2/Y6yPadpng==";
      };
    };
    "@babel/helper-plugin-utils-7.16.7" = {
      name = "_at_babel_slash_helper-plugin-utils";
      packageName = "@babel/helper-plugin-utils";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-plugin-utils/-/helper-plugin-utils-7.16.7.tgz";
        sha512 = "Qg3Nk7ZxpgMrsox6HreY1ZNKdBq7K72tDSliA6dCl5f007jR4ne8iD5UzuNnCJH2xBf2BEEVGr+/OL6Gdp7RxA==";
      };
    };
    "@babel/helper-simple-access-7.16.7" = {
      name = "_at_babel_slash_helper-simple-access";
      packageName = "@babel/helper-simple-access";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-simple-access/-/helper-simple-access-7.16.7.tgz";
        sha512 = "ZIzHVyoeLMvXMN/vok/a4LWRy8G2v205mNP0XOuf9XRLyX5/u9CnVulUtDgUTama3lT+bf/UqucuZjqiGuTS1g==";
      };
    };
    "@babel/helper-split-export-declaration-7.16.7" = {
      name = "_at_babel_slash_helper-split-export-declaration";
      packageName = "@babel/helper-split-export-declaration";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-split-export-declaration/-/helper-split-export-declaration-7.16.7.tgz";
        sha512 = "xbWoy/PFoxSWazIToT9Sif+jJTlrMcndIsaOKvTA6u7QEo7ilkRZpjew18/W3c7nm8fXdUDXh02VXTbZ0pGDNw==";
      };
    };
    "@babel/helper-validator-identifier-7.16.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.16.7.tgz";
        sha512 = "hsEnFemeiW4D08A5gUAZxLBTXpZ39P+a+DGDsHw1yxqyQ/jzFEnxf5uTEGp+3bzAbNOxU1paTgYS4ECU/IgfDw==";
      };
    };
    "@babel/helper-validator-option-7.16.7" = {
      name = "_at_babel_slash_helper-validator-option";
      packageName = "@babel/helper-validator-option";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-option/-/helper-validator-option-7.16.7.tgz";
        sha512 = "TRtenOuRUVo9oIQGPC5G9DgK4743cdxvtOw0weQNpZXaS16SCBi5MNjZF8vba3ETURjZpTbVn7Vvcf2eAwFozQ==";
      };
    };
    "@babel/helpers-7.16.7" = {
      name = "_at_babel_slash_helpers";
      packageName = "@babel/helpers";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helpers/-/helpers-7.16.7.tgz";
        sha512 = "9ZDoqtfY7AuEOt3cxchfii6C7GDyyMBffktR5B2jvWv8u2+efwvpnVKXMWzNehqy68tKgAfSwfdw/lWpthS2bw==";
      };
    };
    "@babel/highlight-7.16.10" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.16.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.16.10.tgz";
        sha512 = "5FnTQLSLswEj6IkgVw5KusNUUFY9ZGqe/TRFnP/BKYHYgfh7tc+C7mwiy95/yNP7Dh9x580Vv8r7u7ZfTBFxdw==";
      };
    };
    "@babel/parser-7.16.12" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.16.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.16.12.tgz";
        sha512 = "VfaV15po8RiZssrkPweyvbGVSe4x2y+aciFCgn0n0/SJMR22cwofRV1mtnJQYcSB1wUTaA/X1LnA3es66MCO5A==";
      };
    };
    "@babel/plugin-syntax-jsx-7.16.7" = {
      name = "_at_babel_slash_plugin-syntax-jsx";
      packageName = "@babel/plugin-syntax-jsx";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-syntax-jsx/-/plugin-syntax-jsx-7.16.7.tgz";
        sha512 = "Esxmk7YjA8QysKeT3VhTXvF6y77f/a91SIs4pWb4H2eWGQkCKFgQaG6hdoEVZtGsrAcb2K5BW66XsOErD4WU3Q==";
      };
    };
    "@babel/plugin-transform-react-jsx-7.16.7" = {
      name = "_at_babel_slash_plugin-transform-react-jsx";
      packageName = "@babel/plugin-transform-react-jsx";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx/-/plugin-transform-react-jsx-7.16.7.tgz";
        sha512 = "8D16ye66fxiE8m890w0BpPpngG9o9OVBBy0gH2E+2AR7qMR2ZpTYJEqLxAsoroenMId0p/wMW+Blc0meDgu0Ag==";
      };
    };
    "@babel/plugin-transform-react-jsx-development-7.16.7" = {
      name = "_at_babel_slash_plugin-transform-react-jsx-development";
      packageName = "@babel/plugin-transform-react-jsx-development";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx-development/-/plugin-transform-react-jsx-development-7.16.7.tgz";
        sha512 = "RMvQWvpla+xy6MlBpPlrKZCMRs2AGiHOGHY3xRwl0pEeim348dDyxeH4xBsMPbIMhujeq7ihE702eM2Ew0Wo+A==";
      };
    };
    "@babel/plugin-transform-react-jsx-self-7.16.7" = {
      name = "_at_babel_slash_plugin-transform-react-jsx-self";
      packageName = "@babel/plugin-transform-react-jsx-self";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx-self/-/plugin-transform-react-jsx-self-7.16.7.tgz";
        sha512 = "oe5VuWs7J9ilH3BCCApGoYjHoSO48vkjX2CbA5bFVhIuO2HKxA3vyF7rleA4o6/4rTDbk6r8hBW7Ul8E+UZrpA==";
      };
    };
    "@babel/plugin-transform-react-jsx-source-7.16.7" = {
      name = "_at_babel_slash_plugin-transform-react-jsx-source";
      packageName = "@babel/plugin-transform-react-jsx-source";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-react-jsx-source/-/plugin-transform-react-jsx-source-7.16.7.tgz";
        sha512 = "rONFiQz9vgbsnaMtQlZCjIRwhJvlrPET8TabIUK2hzlXw9B9s2Ieaxte1SCOOXMbWRHodbKixNf3BLcWVOQ8Bw==";
      };
    };
    "@babel/runtime-7.16.7" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.16.7.tgz";
        sha512 = "9E9FJowqAsytyOY6LG+1KuueckRL+aQW+mKvXRXnuFGyRAyepJPmEo9vgMfXUA6O9u3IeEdv9MAkppFcaQwogQ==";
      };
    };
    "@babel/template-7.16.7" = {
      name = "_at_babel_slash_template";
      packageName = "@babel/template";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/template/-/template-7.16.7.tgz";
        sha512 = "I8j/x8kHUrbYRTUxXrrMbfCa7jxkE7tZre39x3kjr9hvI82cK1FfqLygotcWN5kdPGWcLdWMHpSBavse5tWw3w==";
      };
    };
    "@babel/traverse-7.16.10" = {
      name = "_at_babel_slash_traverse";
      packageName = "@babel/traverse";
      version = "7.16.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/traverse/-/traverse-7.16.10.tgz";
        sha512 = "yzuaYXoRJBGMlBhsMJoUW7G1UmSb/eXr/JHYM/MsOJgavJibLwASijW7oXBdw3NQ6T0bW7Ty5P/VarOs9cHmqw==";
      };
    };
    "@babel/types-7.16.8" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.16.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.16.8.tgz";
        sha512 = "smN2DQc5s4M7fntyjGtyIPbRJv6wW4rU/94fmYJ7PKQuZkC0qGMHXJbg6sNGt12JmVr4k5YaptI/XtiLJBnmIg==";
      };
    };
    "@devexperts/remote-data-ts-2.1.1" = {
      name = "_at_devexperts_slash_remote-data-ts";
      packageName = "@devexperts/remote-data-ts";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@devexperts/remote-data-ts/-/remote-data-ts-2.1.1.tgz";
        sha512 = "z0RblCmeQjYt0vM1g1qR2SzHM1FXZXpBEzokYAojN8n4yC2jIInngeggmqPTOZna2+i7HInDoDm0CGK50W7Llg==";
      };
    };
    "@emotion/cache-11.7.1" = {
      name = "_at_emotion_slash_cache";
      packageName = "@emotion/cache";
      version = "11.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/cache/-/cache-11.7.1.tgz";
        sha512 = "r65Zy4Iljb8oyjtLeCuBH8Qjiy107dOYC6SJq7g7GV5UCQWMObY4SJDPGFjiiVpPrOJ2hmJOoBiYTC7hwx9E2A==";
      };
    };
    "@emotion/hash-0.8.0" = {
      name = "_at_emotion_slash_hash";
      packageName = "@emotion/hash";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/hash/-/hash-0.8.0.tgz";
        sha512 = "kBJtf7PH6aWwZ6fka3zQ0p6SBYzx4fl1LoZXE2RrnYST9Xljm7WfKJrU4g/Xr3Beg72MLrp1AWNUmuYJTL7Cow==";
      };
    };
    "@emotion/memoize-0.7.5" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.5.tgz";
        sha512 = "igX9a37DR2ZPGYtV6suZ6whr8pTFtyHL3K/oLUotxpSVO2ASaprmAe2Dkq7tBo7CRY7MMDrAa9nuQP9/YG8FxQ==";
      };
    };
    "@emotion/react-11.7.1" = {
      name = "_at_emotion_slash_react";
      packageName = "@emotion/react";
      version = "11.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/react/-/react-11.7.1.tgz";
        sha512 = "DV2Xe3yhkF1yT4uAUoJcYL1AmrnO5SVsdfvu+fBuS7IbByDeTVx9+wFmvx9Idzv7/78+9Mgx2Hcmr7Fex3tIyw==";
      };
    };
    "@emotion/serialize-1.0.2" = {
      name = "_at_emotion_slash_serialize";
      packageName = "@emotion/serialize";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/serialize/-/serialize-1.0.2.tgz";
        sha512 = "95MgNJ9+/ajxU7QIAruiOAdYNjxZX7G2mhgrtDWswA21VviYIRP1R5QilZ/bDY42xiKsaktP4egJb3QdYQZi1A==";
      };
    };
    "@emotion/sheet-1.1.0" = {
      name = "_at_emotion_slash_sheet";
      packageName = "@emotion/sheet";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/sheet/-/sheet-1.1.0.tgz";
        sha512 = "u0AX4aSo25sMAygCuQTzS+HsImZFuS8llY8O7b9MDRzbJM0kVJlAz6KNDqcG7pOuQZJmj/8X/rAW+66kMnMW+g==";
      };
    };
    "@emotion/unitless-0.7.5" = {
      name = "_at_emotion_slash_unitless";
      packageName = "@emotion/unitless";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/unitless/-/unitless-0.7.5.tgz";
        sha512 = "OWORNpfjMsSSUBVrRBVGECkhWcULOAJz9ZW8uK9qgxD+87M7jHRcvh/A96XXNhXTLmKcoYSQtBEX7lHMO7YRwg==";
      };
    };
    "@emotion/utils-1.0.0" = {
      name = "_at_emotion_slash_utils";
      packageName = "@emotion/utils";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/utils/-/utils-1.0.0.tgz";
        sha512 = "mQC2b3XLDs6QCW+pDQDiyO/EdGZYOygE8s5N5rrzjSI4M3IejPE/JPndCBwRT9z982aqQNi6beWs1UeayrQxxA==";
      };
    };
    "@emotion/weak-memoize-0.2.5" = {
      name = "_at_emotion_slash_weak-memoize";
      packageName = "@emotion/weak-memoize";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/weak-memoize/-/weak-memoize-0.2.5.tgz";
        sha512 = "6U71C2Wp7r5XtFtQzYrW5iKFT67OixrSxjI4MptCHzdSVlgabczzqLe0ZSgnub/5Kp4hSbpDB1tMytZY9pwxxA==";
      };
    };
    "@mantine/core-3.6.3" = {
      name = "_at_mantine_slash_core";
      packageName = "@mantine/core";
      version = "3.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mantine/core/-/core-3.6.3.tgz";
        sha512 = "puyoIZ6qIIMjaeGHrDgt0rZXpKOpRYdemzVUS9Ss8G+/Ok/Y2CoNwGgbuvOvYFxCHIltQy0+EX0Hs5pNULLKnQ==";
      };
    };
    "@mantine/hooks-3.6.3" = {
      name = "_at_mantine_slash_hooks";
      packageName = "@mantine/hooks";
      version = "3.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mantine/hooks/-/hooks-3.6.3.tgz";
        sha512 = "gxHXPEVUh/gD6VPDnmXnW14IisCk6pe7S2SzksB/3NdlJBCDvBY3j9ORT8hlZPxr+ylAltH6w8EI2SaUdh3T0w==";
      };
    };
    "@mantine/styles-3.6.3" = {
      name = "_at_mantine_slash_styles";
      packageName = "@mantine/styles";
      version = "3.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mantine/styles/-/styles-3.6.3.tgz";
        sha512 = "UvYhBNVy+XdqW8WpjueBEdO7DwY42Ilhl4Hnc0uxeluekqnhy8s+vYXa/7oFGkt2liAeK7tFiVaIX4HS4rYvCQ==";
      };
    };
    "@popperjs/core-2.11.2" = {
      name = "_at_popperjs_slash_core";
      packageName = "@popperjs/core";
      version = "2.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popperjs/core/-/core-2.11.2.tgz";
        sha512 = "92FRmppjjqz29VMJ2dn+xdyXZBrMlE42AV6Kq6BwjWV7CNUW1hs2FtxSNLQE+gJhaZ6AAmYuO9y8dshhcBl7vA==";
      };
    };
    "@radix-ui/number-0.1.0" = {
      name = "_at_radix-ui_slash_number";
      packageName = "@radix-ui/number";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/number/-/number-0.1.0.tgz";
        sha512 = "rpf6QiOWLHAkM4FEMYu9i+5Jr8cKT893+R4mPpcdsy4LD7omr9JfdOqj/h/xPA5+EcVrpMMlU6rrRYpUB5UI8g==";
      };
    };
    "@radix-ui/primitive-0.1.0" = {
      name = "_at_radix-ui_slash_primitive";
      packageName = "@radix-ui/primitive";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/primitive/-/primitive-0.1.0.tgz";
        sha512 = "tqxZKybwN5Fa3VzZry4G6mXAAb9aAqKmPtnVbZpL0vsBwvOHTBwsjHVPXylocYLwEtBY9SCe665bYnNB515uoA==";
      };
    };
    "@radix-ui/react-compose-refs-0.1.0" = {
      name = "_at_radix-ui_slash_react-compose-refs";
      packageName = "@radix-ui/react-compose-refs";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-compose-refs/-/react-compose-refs-0.1.0.tgz";
        sha512 = "eyclbh+b77k+69Dk72q3694OHrn9B3QsoIRx7ywX341U9RK1ThgQjMFZoPtmZNQTksXHLNEiefR8hGVeFyInGg==";
      };
    };
    "@radix-ui/react-context-0.1.1" = {
      name = "_at_radix-ui_slash_react-context";
      packageName = "@radix-ui/react-context";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-context/-/react-context-0.1.1.tgz";
        sha512 = "PkyVX1JsLBioeu0jB9WvRpDBBLtLZohVDT3BB5CTSJqActma8S8030P57mWZb4baZifMvN7KKWPAA40UmWKkQg==";
      };
    };
    "@radix-ui/react-presence-0.1.1" = {
      name = "_at_radix-ui_slash_react-presence";
      packageName = "@radix-ui/react-presence";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-presence/-/react-presence-0.1.1.tgz";
        sha512 = "LsL+NcWDpFUAYCmXeH02o4pgqcSLpwxP84UIjCtpIKrsPe2vLuhcp79KC/jZJeXz+of2lUpMAxpM+eCpxFZtlg==";
      };
    };
    "@radix-ui/react-primitive-0.1.3" = {
      name = "_at_radix-ui_slash_react-primitive";
      packageName = "@radix-ui/react-primitive";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-primitive/-/react-primitive-0.1.3.tgz";
        sha512 = "fcyADaaAx2jdqEDLsTs6aX50S3L1c9K9CC6XMpJpuXFJCU4n9PGTFDZRtY2gAoXXoRCPIBsklCopSmGb6SsDjQ==";
      };
    };
    "@radix-ui/react-scroll-area-0.1.3" = {
      name = "_at_radix-ui_slash_react-scroll-area";
      packageName = "@radix-ui/react-scroll-area";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-scroll-area/-/react-scroll-area-0.1.3.tgz";
        sha512 = "wn5FdX5pU8N6ygqIad4clrhyiLo3LWCdscIee2nKe2bu7AijtUs/VAqmLEoDLIi2gpkS5RclxHbiHRkaxVvccw==";
      };
    };
    "@radix-ui/react-slot-0.1.2" = {
      name = "_at_radix-ui_slash_react-slot";
      packageName = "@radix-ui/react-slot";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-slot/-/react-slot-0.1.2.tgz";
        sha512 = "ADkqfL+agEzEguU3yS26jfB50hRrwf7U4VTwAOZEmi/g+ITcBWe12yM46ueS/UCIMI9Py+gFUaAdxgxafFvY2Q==";
      };
    };
    "@radix-ui/react-use-callback-ref-0.1.0" = {
      name = "_at_radix-ui_slash_react-use-callback-ref";
      packageName = "@radix-ui/react-use-callback-ref";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-use-callback-ref/-/react-use-callback-ref-0.1.0.tgz";
        sha512 = "Va041McOFFl+aV+sejvl0BS2aeHx86ND9X/rVFmEFQKTXCp6xgUK0NGUAGcgBlIjnJSbMYPGEk1xKSSlVcN2Aw==";
      };
    };
    "@radix-ui/react-use-direction-0.1.0" = {
      name = "_at_radix-ui_slash_react-use-direction";
      packageName = "@radix-ui/react-use-direction";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-use-direction/-/react-use-direction-0.1.0.tgz";
        sha512 = "NajpY/An9TCPSfOVkgWIdXJV+VuWl67PxB6kOKYmtNAFHvObzIoh8o0n9sAuwSAyFCZVq211FEf9gvVDRhOyiA==";
      };
    };
    "@radix-ui/react-use-layout-effect-0.1.0" = {
      name = "_at_radix-ui_slash_react-use-layout-effect";
      packageName = "@radix-ui/react-use-layout-effect";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@radix-ui/react-use-layout-effect/-/react-use-layout-effect-0.1.0.tgz";
        sha512 = "+wdeS51Y+E1q1Wmd+1xSSbesZkpVj4jsg0BojCbopWvgq5iBvixw5vgemscdh58ep98BwUbsFYnrywFhV9yrVg==";
      };
    };
    "@rollup/pluginutils-4.1.2" = {
      name = "_at_rollup_slash_pluginutils";
      packageName = "@rollup/pluginutils";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-4.1.2.tgz";
        sha512 = "ROn4qvkxP9SyPeHaf7uQC/GPFY6L/OWy9+bd9AwcjOAWQwxRscoEyAUD8qCY5o5iL4jqQwoLk2kaTKJPb/HwzQ==";
      };
    };
    "@types/node-17.0.12" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.12.tgz";
        sha512 = "4YpbAsnJXWYK/fpTVFlMIcUIho2AYCi4wg5aNPrG1ng7fn/1/RZfCIpRCiBX+12RVa34RluilnvCqD+g3KiSiA==";
      };
    };
    "@types/prop-types-15.7.4" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.4.tgz";
        sha512 = "rZ5drC/jWjrArrS8BR6SIr4cWpW09RNTYt9AMZo3Jwwif+iacXAqgVjm0B0Bv/S1jhDXKHqRVNCbACkJ89RAnQ==";
      };
    };
    "@types/react-17.0.38" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "17.0.38";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-17.0.38.tgz";
        sha512 = "SI92X1IA+FMnP3qM5m4QReluXzhcmovhZnLNm3pyeQlooi02qI7sLiepEYqT678uNiyc25XfCqxREFpy3W7YhQ==";
      };
    };
    "@types/react-dom-17.0.11" = {
      name = "_at_types_slash_react-dom";
      packageName = "@types/react-dom";
      version = "17.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-dom/-/react-dom-17.0.11.tgz";
        sha512 = "f96K3k+24RaLGVu/Y2Ng3e1EbZ8/cVJvypZWd7cy0ofCBaf2lcM46xNhycMZ2xGwbBjRql7hOlZ+e2WlJ5MH3Q==";
      };
    };
    "@types/scheduler-0.16.2" = {
      name = "_at_types_slash_scheduler";
      packageName = "@types/scheduler";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/scheduler/-/scheduler-0.16.2.tgz";
        sha512 = "hppQEBDmlwhFAXKJX2KnWLYu5yMfi91yazPb2l+lbJiwW+wdo1gNeRA+3RgNSO39WYX2euey41KEwnqesU2Jew==";
      };
    };
    "@types/uuid-8.3.4" = {
      name = "_at_types_slash_uuid";
      packageName = "@types/uuid";
      version = "8.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/uuid/-/uuid-8.3.4.tgz";
        sha512 = "c/I8ZRb51j+pYGAu5CrFMRxqZ2ke4y2grEBO5AUjgSkSk+qT2Ea+OdWElz/OiMf5MNpn2b17kuVBwZLQJXzihw==";
      };
    };
    "@vitejs/plugin-react-1.1.4" = {
      name = "_at_vitejs_slash_plugin-react";
      packageName = "@vitejs/plugin-react";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vitejs/plugin-react/-/plugin-react-1.1.4.tgz";
        sha512 = "cMUBDonNY8PPeHWjIrYKbRn6bLSunh/Ixo2XLLBd3DM0uYBZft+c+04zkGhhN1lAwvoRKJ2FdtvhGhPgViHc6w==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "big-integer-1.6.51" = {
      name = "big-integer";
      packageName = "big-integer";
      version = "1.6.51";
      src = fetchurl {
        url = "https://registry.npmjs.org/big-integer/-/big-integer-1.6.51.tgz";
        sha512 = "GPEid2Y9QU1Exl1rpO9B2IPJGHPSupF5GnVIP0blYvNOMer2bTvSWs1jGOUg04hTmu67nmLsQ9TBo1puaotBHg==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "broadcast-channel-3.7.0" = {
      name = "broadcast-channel";
      packageName = "broadcast-channel";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/broadcast-channel/-/broadcast-channel-3.7.0.tgz";
        sha512 = "cIAKJXAxGJceNZGTZSBzMxzyOn72cVgPnKx4dc6LRjQgbaJUQqhy5rzL3zbMxkMWsGKkv2hSFkPRMEXfoMZ2Mg==";
      };
    };
    "browserslist-4.19.1" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.19.1.tgz";
        sha512 = "u2tbbG5PdKRTUoctO3NBD8FQ5HdPh1ZXPHzp1rwaa5jTc+RV9/+RlWiAIKmjRPQF+xbGM9Kklj5bZQFa2s/38A==";
      };
    };
    "caniuse-lite-1.0.30001303" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001303";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001303.tgz";
        sha512 = "/Mqc1oESndUNszJP0kx0UaQU9kEv9nNtJ7Kn8AdA0mNnH8eR1cj0kG+NbNuC1Wq/b21eA8prhKRA3bbkjONegQ==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "clsx-1.1.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-1.1.1.tgz";
        sha512 = "6/bPho624p3S2pMyvP5kKBPXnI3ufHLObBFCfgx+LkeR5lg2XYy2hqZqUf45ypD8COn2bhgGJSUE+l5dhNBieA==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "convert-source-map-1.8.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.8.0.tgz";
        sha512 = "+OQdjP49zViI/6i7nIJpA8rAl4sV/JdPfU9nZs3VqOwGIgizICvuN2ru6fMd+4llL0tar18UYJXfZ/TWtmhUjA==";
      };
    };
    "csstype-3.0.10" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.0.10.tgz";
        sha512 = "2u44ZG2OcNUO9HDp/Jl8C07x6pU/eTR3ncV91SiK3dhG9TWvRVsCoJw14Ckx5DgWkzGA3waZWO3d7pgqpUI/XA==";
      };
    };
    "debug-4.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.3.tgz";
        sha512 = "/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q==";
      };
    };
    "detect-node-2.1.0" = {
      name = "detect-node";
      packageName = "detect-node";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-node/-/detect-node-2.1.0.tgz";
        sha512 = "T0NIuQpnTvFDATNuHN5roPwSBG83rFsuO+MXXH9/3N1eFbn4wcPjttvjMLEPWJ0RGUYgQE7cGgS3tNxbqCGM7g==";
      };
    };
    "electron-to-chromium-1.4.54" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.4.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.54.tgz";
        sha512 = "jRAoneRdSxnpRHO0ANpnEUtQHXxlgfVjrLOnQSisw1ryjXJXvS0pJaR/v2B7S++/tRjgEDp4Sjn5nmgb6uTySw==";
      };
    };
    "esbuild-0.13.15" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.13.15.tgz";
        sha512 = "raCxt02HBKv8RJxE8vkTSCXGIyKHdEdGfUmiYb8wnabnaEmHzyW7DCHb5tEN0xU8ryqg5xw54mcwnYkC4x3AIw==";
      };
    };
    "esbuild-android-arm64-0.13.15" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.13.15.tgz";
        sha512 = "m602nft/XXeO8YQPUDVoHfjyRVPdPgjyyXOxZ44MK/agewFFkPa8tUo6lAzSWh5Ui5PB4KR9UIFTSBKh/RrCmg==";
      };
    };
    "esbuild-darwin-64-0.13.15" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.13.15.tgz";
        sha512 = "ihOQRGs2yyp7t5bArCwnvn2Atr6X4axqPpEdCFPVp7iUj4cVSdisgvEKdNR7yH3JDjW6aQDw40iQFoTqejqxvQ==";
      };
    };
    "esbuild-darwin-arm64-0.13.15" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.13.15.tgz";
        sha512 = "i1FZssTVxUqNlJ6cBTj5YQj4imWy3m49RZRnHhLpefFIh0To05ow9DTrXROTE1urGTQCloFUXTX8QfGJy1P8dQ==";
      };
    };
    "esbuild-freebsd-64-0.13.15" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.13.15.tgz";
        sha512 = "G3dLBXUI6lC6Z09/x+WtXBXbOYQZ0E8TDBqvn7aMaOCzryJs8LyVXKY4CPnHFXZAbSwkCbqiPuSQ1+HhrNk7EA==";
      };
    };
    "esbuild-freebsd-arm64-0.13.15" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.13.15.tgz";
        sha512 = "KJx0fzEDf1uhNOZQStV4ujg30WlnwqUASaGSFPhznLM/bbheu9HhqZ6mJJZM32lkyfGJikw0jg7v3S0oAvtvQQ==";
      };
    };
    "esbuild-linux-32-0.13.15" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.13.15.tgz";
        sha512 = "ZvTBPk0YWCLMCXiFmD5EUtB30zIPvC5Itxz0mdTu/xZBbbHJftQgLWY49wEPSn2T/TxahYCRDWun5smRa0Tu+g==";
      };
    };
    "esbuild-linux-64-0.13.15" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.13.15.tgz";
        sha512 = "eCKzkNSLywNeQTRBxJRQ0jxRCl2YWdMB3+PkWFo2BBQYC5mISLIVIjThNtn6HUNqua1pnvgP5xX0nHbZbPj5oA==";
      };
    };
    "esbuild-linux-arm-0.13.15" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.13.15.tgz";
        sha512 = "wUHttDi/ol0tD8ZgUMDH8Ef7IbDX+/UsWJOXaAyTdkT7Yy9ZBqPg8bgB/Dn3CZ9SBpNieozrPRHm0BGww7W/jA==";
      };
    };
    "esbuild-linux-arm64-0.13.15" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.13.15.tgz";
        sha512 = "bYpuUlN6qYU9slzr/ltyLTR9YTBS7qUDymO8SV7kjeNext61OdmqFAzuVZom+OLW1HPHseBfJ/JfdSlx8oTUoA==";
      };
    };
    "esbuild-linux-mips64le-0.13.15" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.13.15.tgz";
        sha512 = "KlVjIG828uFPyJkO/8gKwy9RbXhCEUeFsCGOJBepUlpa7G8/SeZgncUEz/tOOUJTcWMTmFMtdd3GElGyAtbSWg==";
      };
    };
    "esbuild-linux-ppc64le-0.13.15" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.13.15.tgz";
        sha512 = "h6gYF+OsaqEuBjeesTBtUPw0bmiDu7eAeuc2OEH9S6mV9/jPhPdhOWzdeshb0BskRZxPhxPOjqZ+/OqLcxQwEQ==";
      };
    };
    "esbuild-netbsd-64-0.13.15" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.13.15.tgz";
        sha512 = "3+yE9emwoevLMyvu+iR3rsa+Xwhie7ZEHMGDQ6dkqP/ndFzRHkobHUKTe+NCApSqG5ce2z4rFu+NX/UHnxlh3w==";
      };
    };
    "esbuild-openbsd-64-0.13.15" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.13.15.tgz";
        sha512 = "wTfvtwYJYAFL1fSs8yHIdf5GEE4NkbtbXtjLWjM3Cw8mmQKqsg8kTiqJ9NJQe5NX/5Qlo7Xd9r1yKMMkHllp5g==";
      };
    };
    "esbuild-sunos-64-0.13.15" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.13.15.tgz";
        sha512 = "lbivT9Bx3t1iWWrSnGyBP9ODriEvWDRiweAs69vI+miJoeKwHWOComSRukttbuzjZ8r1q0mQJ8Z7yUsDJ3hKdw==";
      };
    };
    "esbuild-windows-32-0.13.15" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.13.15.tgz";
        sha512 = "fDMEf2g3SsJ599MBr50cY5ve5lP1wyVwTe6aLJsM01KtxyKkB4UT+fc5MXQFn3RLrAIAZOG+tHC+yXObpSn7Nw==";
      };
    };
    "esbuild-windows-64-0.13.15" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.13.15.tgz";
        sha512 = "9aMsPRGDWCd3bGjUIKG/ZOJPKsiztlxl/Q3C1XDswO6eNX/Jtwu4M+jb6YDH9hRSUflQWX0XKAfWzgy5Wk54JQ==";
      };
    };
    "esbuild-windows-arm64-0.13.15" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.13.15.tgz";
        sha512 = "zzvyCVVpbwQQATaf3IG8mu1IwGEiDxKkYUdA4FpoCHi1KtPa13jeScYDjlW0Qh+ebWzpKfR2ZwvqAQkSWNcKjA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fp-ts-2.11.8" = {
      name = "fp-ts";
      packageName = "fp-ts";
      version = "2.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/fp-ts/-/fp-ts-2.11.8.tgz";
        sha512 = "WQT6rP6Jt3TxMdQB3IKzvfZKLuldumntgumLhIUhvPrukTHdWNI4JgEHY04Bd0LIOR9IQRpB+7RuxgUU0Vhmcg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gensync-1.0.0-beta.2" = {
      name = "gensync";
      packageName = "gensync";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensync/-/gensync-1.0.0-beta.2.tgz";
        sha512 = "3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
      };
    };
    "glob-7.2.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.0.tgz";
        sha512 = "lmLf6gtyrPq8tTjSmrO94wBeQbFR3HbLHbuyD69wuyQkImp2hWqMGB47OX65FBkPffO641IP9jWa1z4ivqG26Q==";
      };
    };
    "globals-11.12.0" = {
      name = "globals";
      packageName = "globals";
      version = "11.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-11.12.0.tgz";
        sha512 = "WOBp/EEGUiIsJSp7wcv/y6MO+lV9UoncWqxuFfm8eBwzWNgyfBd6Gz+IeKQ9jCmyhoH99g15M3T+QaVHFjizVA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "history-5.2.0" = {
      name = "history";
      packageName = "history";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-5.2.0.tgz";
        sha512 = "uPSF6lAJb3nSePJ43hN3eKj1dTWpN9gMod0ZssbFTIsen+WehTmEadgL+kg78xLJFdRfrrC//SavDzmRVdE+Ig==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "io-ts-2.2.16" = {
      name = "io-ts";
      packageName = "io-ts";
      version = "2.2.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/io-ts/-/io-ts-2.2.16.tgz";
        sha512 = "y5TTSa6VP6le0hhmIyN0dqEXkrZeJLeC5KApJq6VLci3UEKF80lZ+KuoUs02RhBxNWlrqSNxzfI7otLX1Euv8Q==";
      };
    };
    "io-ts-types-0.5.16" = {
      name = "io-ts-types";
      packageName = "io-ts-types";
      version = "0.5.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/io-ts-types/-/io-ts-types-0.5.16.tgz";
        sha512 = "h9noYVfY9rlbmKI902SJdnV/06jgiT2chxG6lYDxaYNp88HscPi+SBCtmcU+m0E7WT5QSwt7sIMj93+qu0FEwQ==";
      };
    };
    "is-core-module-2.8.1" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.8.1.tgz";
        sha512 = "SdNCUs284hr40hFTFP6l0IfZ/RSrMXF3qgoRHd3/79unUTvrFO/JoXwkGm+5J/Oe3E/b5GsnG330uUNgRpu1PA==";
      };
    };
    "js-sha3-0.8.0" = {
      name = "js-sha3";
      packageName = "js-sha3";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-sha3/-/js-sha3-0.8.0.tgz";
        sha512 = "gF1cRrHhIzNfToc802P800N8PpXS+evLLXfsVpowqmAFR9uwbi89WvXg2QspOmXL8QL86J4T1EpFu+yUkwJY3Q==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsesc-2.5.2" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-2.5.2.tgz";
        sha512 = "OYu7XEzjkCQ3C5Ps3QIZsQfNpqoJyZZA99wd9aWd05NCtC5pWOkShK2mkL6HXQR6/Cy2lbNdPlZBpuQHXE63gA==";
      };
    };
    "json5-2.2.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.0.tgz";
        sha512 = "f+8cldu7X/y7RAJurMEJmdoKXGB/X550w2Nr3tTbezL6RwEE/iMcm+tZnXeoZtKuOq6ft8+CqzEkrIgx1fPoQA==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "match-sorter-6.3.1" = {
      name = "match-sorter";
      packageName = "match-sorter";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/match-sorter/-/match-sorter-6.3.1.tgz";
        sha512 = "mxybbo3pPNuA+ZuCUhm5bwNkXrJTbsk5VWbR5wiwz/GC6LIiegBGn2w3O08UG/jdbYLinw51fSQ5xNU1U3MgBw==";
      };
    };
    "microseconds-0.2.0" = {
      name = "microseconds";
      packageName = "microseconds";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/microseconds/-/microseconds-0.2.0.tgz";
        sha512 = "n7DHHMjR1avBbSpsTBj6fmMGh2AGrifVV4e+WYc3Q9lO+xnSZ3NyhcBND3vzzatt05LFhoKFRxrIyklmLlUtyA==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "monocle-ts-2.3.12" = {
      name = "monocle-ts";
      packageName = "monocle-ts";
      version = "2.3.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/monocle-ts/-/monocle-ts-2.3.12.tgz";
        sha512 = "mf753m69aRNApcL2KCKfLRwfWbraeqQfRRgm3a8D+5lvkhCcMtVp8/vnM04Cmhsd6YXJeInMeQFFETrd7jWYww==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nano-time-1.0.0" = {
      name = "nano-time";
      packageName = "nano-time";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nano-time/-/nano-time-1.0.0.tgz";
        sha1 = "b0554f69ad89e22d0907f7a12b0993a5d96137ef";
      };
    };
    "nanoid-3.2.0" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.2.0.tgz";
        sha512 = "fmsZYa9lpn69Ad5eDn7FMcnnSR+8R34W9qJEijxYhTbfOWzr22n1QxCMzXLK+ODyW2973V3Fux959iQoUxzUIA==";
      };
    };
    "newtype-ts-0.3.5" = {
      name = "newtype-ts";
      packageName = "newtype-ts";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/newtype-ts/-/newtype-ts-0.3.5.tgz";
        sha512 = "v83UEQMlVR75yf1OUdoSFssjitxzjZlqBAjiGQ4WJaML8Jdc68LJ+BaSAXUmKY4bNzp7hygkKLYTsDi14PxI2g==";
      };
    };
    "node-releases-2.0.1" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.1.tgz";
        sha512 = "CqyzN6z7Q6aMeF/ktcMVTzhAHCEpf8SOarwpzpf8pNBY2k5/oM34UHldUwp8VKI7uxct2HxSRdJjBaZeESzcxA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "oblivious-set-1.0.0" = {
      name = "oblivious-set";
      packageName = "oblivious-set";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oblivious-set/-/oblivious-set-1.0.0.tgz";
        sha512 = "z+pI07qxo4c2CulUHCDf9lcqDlMSo72N/4rLUpRXf6fu+q8vjt8y0xS+Tlf8NTJDdTXHbdeO1n3MlbctwEoXZw==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "postcss-8.4.5" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.5.tgz";
        sha512 = "jBDboWM8qpaqwkMwItqTQTiFikhs/67OYVvblFFTM7MrZjt6yMKd6r2kgXizEbTTljacm4NldIlZnhbjr84QYg==";
      };
    };
    "react-17.0.2" = {
      name = "react";
      packageName = "react";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-17.0.2.tgz";
        sha512 = "gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==";
      };
    };
    "react-dom-17.0.2" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-17.0.2.tgz";
        sha512 = "s4h96KtLDUQlsENhMn1ar8t2bEa+q/YAtj8pPPdIjPDGBDIVNsrD9aXNWqspUe6AzKCIG0C1HZZLqLV7qpOBGA==";
      };
    };
    "react-fast-compare-3.2.0" = {
      name = "react-fast-compare";
      packageName = "react-fast-compare";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-fast-compare/-/react-fast-compare-3.2.0.tgz";
        sha512 = "rtGImPZ0YyLrscKI9xTpV8psd6I8VAtjKCzQDlzyDvqJA8XOW78TXYQwNRNd8g8JZnDu8q9Fu/1v4HPAVwVdHA==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-popper-2.2.5" = {
      name = "react-popper";
      packageName = "react-popper";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-popper/-/react-popper-2.2.5.tgz";
        sha512 = "kxGkS80eQGtLl18+uig1UIf9MKixFSyPxglsgLBxlYnyDf65BiY9B3nZSc6C9XUNDgStROB0fMQlTEz1KxGddw==";
      };
    };
    "react-query-3.34.12" = {
      name = "react-query";
      packageName = "react-query";
      version = "3.34.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-query/-/react-query-3.34.12.tgz";
        sha512 = "flDdudQVH4CqE+kNYYYyo4g2Yjek3H/36G3b9bK5oe26jD5gFnx+PPwnq0gayq5z2dcSfr2z4+drvuyeZ3A5QQ==";
      };
    };
    "react-refresh-0.11.0" = {
      name = "react-refresh";
      packageName = "react-refresh";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-refresh/-/react-refresh-0.11.0.tgz";
        sha512 = "F27qZr8uUqwhWZboondsPx8tnC3Ct3SxZA3V5WyEvujRyyNv0VYPhoBg1gZ8/MV5tubQp76Trw8lTv9hzRBa+A==";
      };
    };
    "react-router-6.2.1" = {
      name = "react-router";
      packageName = "react-router";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-6.2.1.tgz";
        sha512 = "2fG0udBtxou9lXtK97eJeET2ki5//UWfQSl1rlJ7quwe6jrktK9FCCc8dQb5QY6jAv3jua8bBQRhhDOM/kVRsg==";
      };
    };
    "react-router-dom-6.2.1" = {
      name = "react-router-dom";
      packageName = "react-router-dom";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-6.2.1.tgz";
        sha512 = "I6Zax+/TH/cZMDpj3/4Fl2eaNdcvoxxHoH1tYOREsQ22OKDYofGebrNm6CTPUcvLvZm63NL/vzCYdjf9CUhqmA==";
      };
    };
    "react-textarea-autosize-8.3.3" = {
      name = "react-textarea-autosize";
      packageName = "react-textarea-autosize";
      version = "8.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-textarea-autosize/-/react-textarea-autosize-8.3.3.tgz";
        sha512 = "2XlHXK2TDxS6vbQaoPbMOfQ8GK7+irc2fVK6QFIcC8GOnH3zI/v481n+j1L0WaPVvKxwesnY93fEfH++sus2rQ==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "remove-accents-0.4.2" = {
      name = "remove-accents";
      packageName = "remove-accents";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-accents/-/remove-accents-0.4.2.tgz";
        sha1 = "0a43d3aaae1e80db919e07ae254b285d9e1c7bb5";
      };
    };
    "resolve-1.22.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.0.tgz";
        sha512 = "Hhtrw0nLeSrFQ7phPp4OOcVjLPIeMnRlr5mcnVuMe7M/7eBn98A3hmFRLoFo3DLZkivSYwhRUJTyPyWAk56WLw==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "rollup-2.66.1" = {
      name = "rollup";
      packageName = "rollup";
      version = "2.66.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-2.66.1.tgz";
        sha512 = "crSgLhSkLMnKr4s9iZ/1qJCplgAgrRY+igWv8KhG/AjKOJ0YX/WpmANyn8oxrw+zenF3BXWDLa7Xl/QZISH+7w==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "scheduler-0.20.2" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.20.2.tgz";
        sha512 = "2eWfGgAqqWFGqtdMmcL5zCMK1U8KlXv8SQFGglL3CEtd0aDVDWgeF/YoCmvln55m5zSk3J/20hTaSBeSObsQDQ==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "stylis-4.0.13" = {
      name = "stylis";
      packageName = "stylis";
      version = "4.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-4.0.13.tgz";
        sha512 = "xGPXiFVl4YED9Jh7Euv2V220mriG9u4B2TA6Ybjc1catrstKD2PpIdU3U0RKpkVBC2EhmL/F0sPCr9vrFTNRag==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "typescript-4.5.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.5.5.tgz";
        sha512 = "TCTIul70LyWe6IJWT8QSYeA54WQe8EjQFU4wY52Fasj5UKx88LNYKCgBEHcOMOrFF1rKGbD8v/xcNWVUq9SymA==";
      };
    };
    "unload-2.2.0" = {
      name = "unload";
      packageName = "unload";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unload/-/unload-2.2.0.tgz";
        sha512 = "B60uB5TNBLtN6/LsgAf3udH9saB5p7gqJwcFfbOEZ8BcBHnGwCf6G/TGiEqkRAxX7zAFIUtzdrXQSdL3Q/wqNA==";
      };
    };
    "use-composed-ref-1.2.1" = {
      name = "use-composed-ref";
      packageName = "use-composed-ref";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-composed-ref/-/use-composed-ref-1.2.1.tgz";
        sha512 = "6+X1FLlIcjvFMAeAD/hcxDT8tmyrWnbSPMU0EnxQuDLIxokuFzWliXBiYZuGIx+mrAMLBw0WFfCkaPw8ebzAhw==";
      };
    };
    "use-isomorphic-layout-effect-1.1.1" = {
      name = "use-isomorphic-layout-effect";
      packageName = "use-isomorphic-layout-effect";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-isomorphic-layout-effect/-/use-isomorphic-layout-effect-1.1.1.tgz";
        sha512 = "L7Evj8FGcwo/wpbv/qvSfrkHFtOpCzvM5yl2KVyDJoylVuSvzphiiasmjgQPttIGBAy2WKiBNR98q8w7PiNgKQ==";
      };
    };
    "use-latest-1.2.0" = {
      name = "use-latest";
      packageName = "use-latest";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-latest/-/use-latest-1.2.0.tgz";
        sha512 = "d2TEuG6nSLKQLAfW3By8mKr8HurOlTkul0sOpxbClIv4SQ4iOd7BYr7VIzdbktUCnv7dua/60xzd8igMU6jmyw==";
      };
    };
    "uuid-8.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz";
        sha512 = "+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==";
      };
    };
    "vite-2.7.13" = {
      name = "vite";
      packageName = "vite";
      version = "2.7.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite/-/vite-2.7.13.tgz";
        sha512 = "Mq8et7f3aK0SgSxjDNfOAimZGW9XryfHRa/uV0jseQSilg+KhYDSoNb9h1rknOy6SuMkvNDLKCYAYYUMCE+IgQ==";
      };
    };
    "warning-4.0.3" = {
      name = "warning";
      packageName = "warning";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-4.0.3.tgz";
        sha512 = "rpJyN222KWIvHJ/F53XSZv0Zl/accqHR8et1kpaMTD/fLCRxtV8iX8czMzY7sVZupTI3zcUTg8eycS2kNF9l6w==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
  args = {
    name = "simple-survey";
    packageName = "simple-survey";
    version = "0.0.0";
    src = ./..;
    dependencies = [
      sources."@babel/code-frame-7.16.7"
      sources."@babel/compat-data-7.16.8"
      sources."@babel/core-7.16.12"
      sources."@babel/generator-7.16.8"
      sources."@babel/helper-annotate-as-pure-7.16.7"
      sources."@babel/helper-compilation-targets-7.16.7"
      sources."@babel/helper-environment-visitor-7.16.7"
      sources."@babel/helper-function-name-7.16.7"
      sources."@babel/helper-get-function-arity-7.16.7"
      sources."@babel/helper-hoist-variables-7.16.7"
      sources."@babel/helper-module-imports-7.16.7"
      sources."@babel/helper-module-transforms-7.16.7"
      sources."@babel/helper-plugin-utils-7.16.7"
      sources."@babel/helper-simple-access-7.16.7"
      sources."@babel/helper-split-export-declaration-7.16.7"
      sources."@babel/helper-validator-identifier-7.16.7"
      sources."@babel/helper-validator-option-7.16.7"
      sources."@babel/helpers-7.16.7"
      sources."@babel/highlight-7.16.10"
      sources."@babel/parser-7.16.12"
      sources."@babel/plugin-syntax-jsx-7.16.7"
      sources."@babel/plugin-transform-react-jsx-7.16.7"
      sources."@babel/plugin-transform-react-jsx-development-7.16.7"
      sources."@babel/plugin-transform-react-jsx-self-7.16.7"
      sources."@babel/plugin-transform-react-jsx-source-7.16.7"
      sources."@babel/runtime-7.16.7"
      sources."@babel/template-7.16.7"
      sources."@babel/traverse-7.16.10"
      sources."@babel/types-7.16.8"
      sources."@devexperts/remote-data-ts-2.1.1"
      sources."@emotion/cache-11.7.1"
      sources."@emotion/hash-0.8.0"
      sources."@emotion/memoize-0.7.5"
      sources."@emotion/react-11.7.1"
      sources."@emotion/serialize-1.0.2"
      sources."@emotion/sheet-1.1.0"
      sources."@emotion/unitless-0.7.5"
      sources."@emotion/utils-1.0.0"
      sources."@emotion/weak-memoize-0.2.5"
      sources."@mantine/core-3.6.3"
      sources."@mantine/hooks-3.6.3"
      sources."@mantine/styles-3.6.3"
      sources."@popperjs/core-2.11.2"
      sources."@radix-ui/number-0.1.0"
      sources."@radix-ui/primitive-0.1.0"
      sources."@radix-ui/react-compose-refs-0.1.0"
      sources."@radix-ui/react-context-0.1.1"
      sources."@radix-ui/react-presence-0.1.1"
      sources."@radix-ui/react-primitive-0.1.3"
      sources."@radix-ui/react-scroll-area-0.1.3"
      sources."@radix-ui/react-slot-0.1.2"
      sources."@radix-ui/react-use-callback-ref-0.1.0"
      sources."@radix-ui/react-use-direction-0.1.0"
      sources."@radix-ui/react-use-layout-effect-0.1.0"
      sources."@rollup/pluginutils-4.1.2"
      sources."@types/node-17.0.12"
      sources."@types/prop-types-15.7.4"
      sources."@types/react-17.0.38"
      sources."@types/react-dom-17.0.11"
      sources."@types/scheduler-0.16.2"
      sources."@types/uuid-8.3.4"
      sources."@vitejs/plugin-react-1.1.4"
      sources."ansi-styles-3.2.1"
      sources."balanced-match-1.0.2"
      sources."big-integer-1.6.51"
      sources."brace-expansion-1.1.11"
      sources."broadcast-channel-3.7.0"
      sources."browserslist-4.19.1"
      sources."caniuse-lite-1.0.30001303"
      sources."chalk-2.4.2"
      sources."clsx-1.1.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."convert-source-map-1.8.0"
      sources."csstype-3.0.10"
      sources."debug-4.3.3"
      sources."detect-node-2.1.0"
      sources."electron-to-chromium-1.4.54"
      sources."esbuild-0.13.15"
      sources."esbuild-android-arm64-0.13.15"
      sources."esbuild-darwin-64-0.13.15"
      sources."esbuild-darwin-arm64-0.13.15"
      sources."esbuild-freebsd-64-0.13.15"
      sources."esbuild-freebsd-arm64-0.13.15"
      sources."esbuild-linux-32-0.13.15"
      sources."esbuild-linux-64-0.13.15"
      sources."esbuild-linux-arm-0.13.15"
      sources."esbuild-linux-arm64-0.13.15"
      sources."esbuild-linux-mips64le-0.13.15"
      sources."esbuild-linux-ppc64le-0.13.15"
      sources."esbuild-netbsd-64-0.13.15"
      sources."esbuild-openbsd-64-0.13.15"
      sources."esbuild-sunos-64-0.13.15"
      sources."esbuild-windows-32-0.13.15"
      sources."esbuild-windows-64-0.13.15"
      sources."esbuild-windows-arm64-0.13.15"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."estree-walker-2.0.2"
      sources."fp-ts-2.11.8"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."gensync-1.0.0-beta.2"
      sources."glob-7.2.0"
      sources."globals-11.12.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."history-5.2.0"
      sources."hoist-non-react-statics-3.3.2"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."io-ts-2.2.16"
      sources."io-ts-types-0.5.16"
      sources."is-core-module-2.8.1"
      sources."js-sha3-0.8.0"
      sources."js-tokens-4.0.0"
      sources."jsesc-2.5.2"
      sources."json5-2.2.0"
      sources."loose-envify-1.4.0"
      sources."match-sorter-6.3.1"
      sources."microseconds-0.2.0"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."monocle-ts-2.3.12"
      sources."ms-2.1.2"
      sources."nano-time-1.0.0"
      sources."nanoid-3.2.0"
      sources."newtype-ts-0.3.5"
      sources."node-releases-2.0.1"
      sources."object-assign-4.1.1"
      sources."oblivious-set-1.0.0"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.1"
      sources."postcss-8.4.5"
      sources."react-17.0.2"
      sources."react-dom-17.0.2"
      sources."react-fast-compare-3.2.0"
      sources."react-is-16.13.1"
      sources."react-popper-2.2.5"
      sources."react-query-3.34.12"
      sources."react-refresh-0.11.0"
      sources."react-router-6.2.1"
      sources."react-router-dom-6.2.1"
      sources."react-textarea-autosize-8.3.3"
      sources."regenerator-runtime-0.13.9"
      sources."remove-accents-0.4.2"
      sources."resolve-1.22.0"
      sources."rimraf-3.0.2"
      sources."rollup-2.66.1"
      sources."safe-buffer-5.1.2"
      sources."scheduler-0.20.2"
      sources."semver-6.3.0"
      sources."source-map-0.5.7"
      sources."source-map-js-1.0.2"
      sources."stylis-4.0.13"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."to-fast-properties-2.0.0"
      sources."typescript-4.5.5"
      sources."unload-2.2.0"
      sources."use-composed-ref-1.2.1"
      sources."use-isomorphic-layout-effect-1.1.1"
      sources."use-latest-1.2.0"
      sources."uuid-8.3.2"
      sources."vite-2.7.13"
      sources."warning-4.0.3"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
