name: simpleSurvey-server
version: 0.0.1

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - SimpleSurvey
    - SimpleSurvey.Config
    - SimpleSurvey.Database
    - SimpleSurvey.Init
    - SimpleSurvey.Logger
    - SimpleSurvey.App
    - SimpleSurvey.Base.Error
    - SimpleSurvey.Base.Models
    - SimpleSurvey.Auth.Domain.Models
    - SimpleSurvey.Auth.Domain.Commands.SignUpUser
    - SimpleSurvey.Auth.Domain.Queries.LoginUser
    - SimpleSurvey.Auth.API
    - SimpleSurvey.Auth.Repository.Persist.Postgres
    - SimpleSurvey.Auth.Repository.UserRepository
    - Util.Database.Persist.Postgresql.Json


executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - simpleSurvey-server

tests:
  tests:
    main: Main.hs
    source-dirs: tests

    dependencies:
      - base
      - hspec
      - simpleSurvey-server
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - servant-multipart
  - http-client
  - utf8-string
  - password
  - password-instances
  - password-types
  - persistent
  - persistent-template
  - persistent-postgresql
  - monad-logger
  - monad-metrics
  - esqueleto
  - aeson
  - wai
  - wai-extra
  - text
  - warp
  - http-api-data
  - bytestring
  - containers
  - QuickCheck
  - quickcheck-arbitrary-adt
  - wai-cors
  - mtl
  - katip
  - say
  - fast-logger
  - safe-exceptions
  - safe
  - ekg
  - wai-middleware-metrics
  - resource-pool
  - microlens
  - hspec
  - servant-auth
  - servant-auth-server
  - time
  - quickcheck-text
