name: simpleSurvey-server
version: 0.0.1

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - SS

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - simpleSurvey-server

tests:
  tests:
    main: Main.hs
    source-dirs: tests

    dependencies:
      - base
      - hspec
      - simpleSurvey-server
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

dependencies:
  - base
  - postgresql-simple
  - postgresql-simple-migration
  - servant
  - servant-server
  - transformers
  - servant-multipart
  - http-client
  - utf8-string
  - password
  - password-instances
  - password-types
  - monad-logger
  - monad-metrics
  - aeson
  - wai
  - wai-extra
  - text
  - warp
  - http-api-data
  - bytestring
  - containers
  - cereal
  - cryptonite
  - QuickCheck
  - quickcheck-arbitrary-adt
  - wai-cors
  - mtl
  - katip
  - say
  - fast-logger
  - safe-exceptions
  - safe
  - resource-pool
  - microlens
  - hspec
  - servant-auth
  - servant-auth-server
  - time
  - quickcheck-text

default-extensions:
  - DataKinds
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - FlexibleContexts
  - OverloadedStrings
  - FlexibleInstances
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - UndecidableInstances
  - TypeFamilies
  - TypeOperators